# sudo docker run -d -p 9200:9200 -p 9300:9300 -v `pwd`/../datas/:/datas --name coursestovacuum_elastic_1 coursestovacuum_elastic
elastic:
  build: ./elasticsearch
  volumes:
    - ./datas/:/datas
  expose:
    - "9300:9300"
    - "9200:9200"

# sudo docker run -d -p 27017:27017 -v `pwd`/../datas/:/datas --name coursestovacuum_mongod_1 coursestovacuum_mongod
mongod:
  build: ./mongod
  volumes:
    - ./datas/:/datas
  expose:
    - "27017:27017"

# sudo docker run -d -p 6379:6379 -v `pwd`/../datas/:/datas --name coursestovacuum_redis_1 coursestovacuum_redis
redis:
  build: ./redis
  volumes:
    - ./datas/:/datas
  expose:
    - "6379:6379"

# sudo docker run -it -v `pwd`/src/:/datas --link coursestovacuum_redis_1:REDIS_1 --link coursestovacuum_nodeserver_1:NODESERVER_1 coursestovacuum_job /sbin/my_init -- /bin/bash -l
job:
  build: ./job
  volumes:
    - ./src/:/datas
  links:
    - redis
    - nodeserver

nodeserver:
  build: ./node
  volumes:
    - ./datas:/datas
    - ./src:/execs
  expose:
    - "8811:8811"
  links:
    - redis




firstjob:
  build: ./start_first_job
  volumes:
    - ./src/:/datas
  links:
    - nodeserver




# sudo docker run -it -p 8282:8282 -v `pwd`/src/:/execs -v `pwd`/datas/:/datas --link coursestovacuum_redis_1:REDIS_1 --link coursestovacuum_mongod_1:MONGOD_1 --link coursestovacuum_elastic_1:ELASTIC_1 coursestovacuum_railsserver /sbin/my_init -- /bin/bash -l
railsserver:
  build: ./rails
  volumes:
    - ./datas:/datas
    - ./src:/execs
  ports:
    - "8282:8282"
  links:
    - mongod
    - elastic
    - redis


# sudo docker run -it -v `pwd`/src/:/execs -v `pwd`/datas/:/datas --link coursestovacuum_redis_1:REDIS_1 --link coursestovacuum_mongod_1:MONGOD_1 --link coursestovacuum_elastic_1:ELASTIC_1 coursestovacuum_sidekiq /sbin/my_init -- /bin/bash -l
sidekiq:
  build: ./sidekiq
  volumes:
    - ./datas:/datas
    - ./src:/execs
  links:
    - mongod
    - elastic
    - redis

# sudo docker run -it -v `pwd`/src/:/execs -v `pwd`/datas/:/datas --link coursestovacuum_redis_1:REDIS_1 --link coursestovacuum_mongod_1:MONGOD_1 --link coursestovacuum_elastic_1:ELASTIC_1 coursestovacuum_sidekiq /sbin/my_init -- /bin/bash -l
nginx:
  build: ./nginx
  volumes:
    - ./datas:/datas
    - ./src:/execs
  links:
    - mongod
    - elastic
    - redis
